In [1]:
import numpy as np
import pandas as pd


ModuleNotFoundError: No module named 'tensorflow.python'

In [4]:
a = np.array([[1,2,3,4],[4,5,6,7]])

In [5]:
a.shape
#(row,column)

(2, 4)

In [6]:
a.dtype
# Shows the datatype used

dtype('int32')

In [7]:
np.ones((4,4),dtype=int)
# for generating 4x4 matrix of ones
# dtype can be str, bool, int, float


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [8]:
np.zeros((5,5),dtype=bool)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [9]:
np.empty((3,3))
# Random values

array([[nan,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

arange()


In [10]:
arr1 = np.arange(start=1,stop=12,step=2)
# From [1,12) with step of 2

linspace()

linspace is a function commonly used in numerical computing to generate an array of evenly spaced values over a specified interval


In [11]:
np.linspace(1,5,40,dtype=float)

array([1.        , 1.1025641 , 1.20512821, 1.30769231, 1.41025641,
       1.51282051, 1.61538462, 1.71794872, 1.82051282, 1.92307692,
       2.02564103, 2.12820513, 2.23076923, 2.33333333, 2.43589744,
       2.53846154, 2.64102564, 2.74358974, 2.84615385, 2.94871795,
       3.05128205, 3.15384615, 3.25641026, 3.35897436, 3.46153846,
       3.56410256, 3.66666667, 3.76923077, 3.87179487, 3.97435897,
       4.07692308, 4.17948718, 4.28205128, 4.38461538, 4.48717949,
       4.58974359, 4.69230769, 4.79487179, 4.8974359 , 5.        ])

reshape()

The reshape() function in NumPy is used to change the shape of an existing array without changing its data.


In [12]:
arr = np.arange(12)
reshaped_arr = arr.reshape((4, 3)) # 1D to 2D

In [13]:
reshaped_arr2 = arr.reshape((2, 3, 2)) # 1D to 2D


In [14]:
reshaped_arr.reshape((2,3,2)) # 2D to 3D

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

ravel()

The ravel() function in NumPy is used to flatten a multi-dimensional array into a one-dimensional array. 



In [15]:
reshaped_arr.ravel() # flattend
reshaped_arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

flatten()

The flatten() method in NumPy is used to create a flattened version of a multi-dimensional array, returning a new one-dimensional array. Unlike ravel(), which returns a flattened array that is a view of the original array whenever possible, flatten() always returns a copy of the data.



In [16]:
reshaped_arr2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

transpose()

The transpose() function in NumPy is used to reverse the axes of an array. It returns a view of the original array with the axes permuted according to the specified order. Transposing an array changes its shape but not its data.



In [17]:
transposed_arr = reshaped_arr.transpose()
print(f" Intial array : {reshaped_arr}")
transposed_arr

 Intial array : [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [18]:
transposed_arr.T # Can also transpose like this

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Mathematics using numpy

In [19]:
ar1 = np.arange(1,10).reshape(3,3)
ar2 = np.arange(1,10).reshape(3,3)
print(ar1)
print()
print(ar2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
ar1 + ar2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [21]:
np.add(ar1,ar2)
# Same as above

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [22]:
ar1 - ar2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
ar1/ar2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
ar1 * ar2
# Scalar Product

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [25]:
ar1 @ ar2
# Cross Product

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [26]:
ar1.max()


9

Column Wise concatenation


In [28]:
np.concatenate((ar1,ar2))
# axis  = 0 by deafualt meaing it will do column wise

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
np.vstack((ar1,ar2))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Row wise Concatenation


In [30]:
np.concatenate((ar1,ar2),axis=1)
# Row wise

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [33]:
np.hstack((ar1,ar2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

Splitting Array

In [35]:
np.split(ar1,3,axis=1)
# Spliting an array in 3 parts use axis to decide row or column


[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]